### ISSUE TITLE
if isinstance(container._parent, _Cell): gives error

### ISSUE THREAD

**Issue by tooh** [fokoenecke/html_docx#1]
```
line 35, in get_new_paragraph
    if isinstance(container._parent, _Cell):
AttributeError: 'Paragraph' object has no attribute '_parent'
```

**Comment by fokoenecke** [comment]
Strange, because Paragraph is a `Parented` class and should therefore should have a `_parent` attribute.

> class Parented(object):
> Provides common services for document elements that occur below a part but may occasionally require an ancestor object to provide a service, such as add or drop a relationship. Provides `self._parent` attribute to subclasses.

I will have a look at it.

**Comment by tooh** [comment]
@fokoenecke 
Found it. My mistake. I work on 2 different machines. Forgot to update python-docx. Sorry. Issue can be closed.
